name: Go CI

on:
  workflow_call:
    inputs:
      go-version:
        type: string
        default: '1.22'
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          cache: true

      - name: Run vet
        run: go vet ./...

      - name: Run tests
        run: go test -v ./...
