name: Java CI

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        default: '17'
        required: false
      build-tool:
        type: string
        default: 'maven'
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: ${{ inputs.build-tool }}

      - name: Build and Test with Maven
        if: inputs.build-tool == 'maven'
        run: mvn clean test

      - name: Build and Test with Gradle
        if: inputs.build-tool == 'gradle'
        run: ./gradlew test
